#pragma once

#define OFFSET_UWORLD 0x78
#define OFFSET_GAMEINSTANCE 0x1A8
#define OFFSET_LOCALPLAYER 0x38
#define OFFSET_PLAYERCONTROLLER 0x30
#define OFFSET_PAWN 0x2A0
#define OFFSET_ACTOR_ARRAY 0x98
#define OFFSET_ACTOR_COUNT 0xA0
#define OFFSET_ROOTCOMPONENT 0x140
#define OFFSET_POSITION 0x11C
#define OFFSET_MESH 0x288
#define OFFSET_TEAMID 0x7E8
#define OFFSET_HEALTH 0x1A8
#define OFFSET_NAME 0x18